# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1ecbc18807f7845c100fda40702663c8ccec156f4a881986c5af29568d73808783e4479ec4f18c3f9ec8a79fd6c1044151c40eb4d25f00b8e62f153f89739ca

test:
  secret_key_base: 2c867c891b9ef370094eb8c8aea8de72a77dfb1e580df1100fbbe72a9e985c5673c45939c5736d52587c908487abc0a1daf530619fe135d00b963c45b1fbfda9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
